name: Checks

on:
    pull_request:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: checks
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install checkers
      run: pip install "black<23" pylint==v3.0.0a3 mypy==v0.902
    - name: Run black
      run: black --diff --check $(git ls-files '*.py')
    - name: Run pylint
      run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
    - name: Run mypy
      run: mypy --strict $(git ls-files '*.py')